name: cappy_tax
description: "A new Flutter project for tax management."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  supabase_flutter: ^2.0.0
  camera: ^0.10.5+5
  camera_web: ^0.3.2+4
  http: ^1.1.0
  go_router: ^12.0.0
  google_fonts: ^6.1.0
  # State & Logic
  flutter_riverpod: ^2.5.0
  dio: ^5.4.0
  path_provider: ^2.1.1
  path: ^1.8.3
  flutter_dotenv: ^6.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
